name: fooddelivery_b
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/efood.png
    - assets/images/add.png
    - assets/images/app_logo.png
    - assets/images/cat_offer.png
    - assets/images/cat_sri.png
    - assets/images/cat_3.png
    - assets/images/cat_4.png
    - assets/images/res_1.png
    - assets/images/res_2.png
    - assets/images/res_3.png
    - assets/images/m_res_1.png
    - assets/images/m_res_2.png
    - assets/images/item_1.png
    - assets/images/item_2.png
    - assets/images/item_3.png
    - assets/images/aadarsha.jpeg

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
