name: fooddelivery_b
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.0
  dartz: ^0.10.1
  fluttertoast: ^8.2.4


  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  permission_handler: ^12.0.0+1
  equatable: ^2.0.7
  get_it: ^8.0.3


  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  json_serializable: ^6.9.0
  bloc: ^9.0.0
  provider: ^6.1.5
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-ExtraBold.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
        - asset: assets/fonts/Metropolis-Medium.otf
