name: fooddelivery_b
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  flutter_timezone: ^1.0.6
  shared_preferences: ^2.2.2
  get_it: ^7.6.0 
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-ExtraBold.otf  
        - asset: assets/fonts/Metropolis-Medium.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
