import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:fooddelivery_b/features/food_products/domain/entity/products_entity.dart';
import 'package:fooddelivery_b/features/food_products/presentation/state/product_state.dart';
import 'package:fooddelivery_b/features/food_products/presentation/view_model/product_event.dart';
import 'package:fooddelivery_b/widgets/product_card.dart';
import 'package:fooddelivery_b/features/cart/presentation/view_model/cart_view_model.dart';
import 'package:fooddelivery_b/features/cart/presentation/event/cart_event.dart';
import 'package:fooddelivery_b/features/cart/domain/entity/cart_item_entity.dart';
import 'package:fooddelivery_b/features/cart/presentation/widgets/cart_dialog.dart';
import 'package:fooddelivery_b/features/cart/presentation/widgets/add_to_cart_icon_button.dart';

import 'product_viewmodel.dart';

class ProductListView extends StatelessWidget {
  final ProductViewModel viewModel;
  final String categoryId;

  const ProductListView({
    Key? key,
    required this.viewModel,
    required this.categoryId,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Trigger loading when the widget is built
    WidgetsBinding.instance.addPostFrameCallback((_) {
      viewModel.onEvent(LoadProductsByCategory(categoryId));
    });

    return AnimatedBuilder(
      animation: viewModel,
      builder: (context, _) {
        final state = viewModel.state;
        if (state is ProductLoading) {
          return const Center(child: CircularProgressIndicator());
        } else if (state is ProductLoaded) {
          if (state.products.isEmpty) {
            return const Center(child: Text('No products found in this category.'));
          }
          return ListView.builder(
            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
            itemCount: state.products.length,
            itemBuilder: (context, index) {
              final product = state.products[index];
              
              return ProductCard(
                product: {
                  'productId': product.productId,
                  'name': product.name,
                  'type': product.type,
                  'price': product.price,
                  'description': product.description,
                  'image': product.image,
                  'isAvailable': product.isAvailable,
                  'restaurantId': product.restaurantId,
                  'restaurantName': product.restaurantName,
                  'restaurantImage': product.restaurantImage,
                  'categoryId': product.categoryId,
                  'categoryName': product.categoryName,
                },
                onAddToCart: () {
                  _addToCartAndShowDialog(context, product);
                },
              );
            },
          );
        } else if (state is ProductError) {
          return Center(child: Text(state.message));
        }
        return const SizedBox.shrink();
      },
    );
  }

  void _addToCartAndShowDialog(BuildContext context, ProductsEntity product) async {
    try {
      // Get the CartViewModel from the provider using Consumer
      final cartViewModel = context.read<CartViewModel>();
      
      // Create cart item from product
      final cartItem = CartItemEntity(
        cartItemId: null, // Will be generated by backend
        product: product,
        quantity: 1,
        price: product.price,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // Add to cart using the cart view model
      await cartViewModel.onEvent(AddToCart(cartItem));
      
      // Show success message
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${product.name} added to cart!'),
            backgroundColor: Colors.green,
            duration: const Duration(seconds: 2),
            action: SnackBarAction(
              label: 'View Cart',
              textColor: Colors.white,
              onPressed: () {
                // Show cart dialog
                CartDialog.show(context);
              },
            ),
          ),
        );

        // Show cart dialog immediately
        CartDialog.show(context);
      }
    } catch (error) {
      // Handle error
      print('Error adding to cart: $error');
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to add ${product.name} to cart: $error'),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 2),
          ),
        );
      }
    }
  }
}